### ISSUE TITLE
adding video html5 tag

### ISSUE THREAD

**Issue by omgbox** [dafiulh/vredeburg#1]
hi, im trying to figure where the thumb code is and replace it with a html5 video tag,

how would i remove the thumb while user views post

**Comment by dafiulh** [comment]
Sorry, I don't understand. Do you want to replace thumbnail with video?

**Comment by omgbox** [comment]
> Sorry, I don't understand. Do you want to replace thumbnail with video?

its fine, i found the code, i just wanted to disable the thumbnail which is shown on post. 

> Sorry, I don't understand. Do you want to replace thumbnail with video?

my apologies, found it here 
vredeburg/src/_includes/partials/post-grid.njk

thank you.
