### ISSUE TITLE
video versioned of this template.

### ISSUE THREAD

**Issue by omgbox** [dafiulh/vredeburg#2]
hello friend, is it possible you can make another theme based on vredeburg but for video. which looks like this, i want to share anime and i want to display 4 small thumbs on the front page with tags . 
![Image of Yaktocat](https://siasky.net/fAKUF1GXHWGOI7pUIoXipC2mz_oITjePcvChmGjcE5HICA)

**Comment by dafiulh** [comment]
Hmm... you can change the code in `src / _includes / partials / post-grid.njk`
But why do you need 4 thumbnails for each anime?

**Comment by omgbox** [comment]
> Hmm... you can change the code in `src / _includes / partials / post-grid.njk`
> But why do you need 4 thumbnails for each anime?

thanks i figured it out, now i just need to change the css, i want to show different times in video with 4 thumbnails it is just something i like to do it is nothing specific. 

thanks
