### ISSUE TITLE
CSS Build Problem

### ISSUE THREAD

**Issue by xanderyzwich** [dafiulh/vredeburg#8]
After having used the 'Use as template' option to create [my repository](https://github.com/xanderyzwich/dev-booklist), the main.css is not functioning with the existing build as I'm attempting to run in local. I would appreciate it if you might have the time to assist.

**Comment by dafiulh** [comment]
I've tried to clone your repository and it works fine. Make sure you have installed all dependencies by running `npm install`.
If that still doesn't work, can you please send me the error message you got? Because I can't tell what do you mean by "not functioning".

**Comment by dafiulh** [comment]
Is this still an issue? I will close this if it isn't
