### ISSUE TITLE
Folders inside /src/posts/img/ ?

### ISSUE THREAD

**Issue by TedGoas** [dafiulh/vredeburg#9]
Hi, thanks so much for providing this starter template! I'm using it to rebuild my personal site, which includes a blog. Some of my blog posts contain a bunch of images, so I typically put them into a their own folder to keep the root image directory clean.

However I notice that images inside a folder inside `/src/posts/img/` can't be loaded.

Eg. if I reference a thumb in front matter like `thumb: "image.svg"` it displays, but if I put it into a folder inside `/img/` and reference it like `thumb: "folder/image.svg"` it cannot be displayed.

The strange thing is that the image path created appears to be correct:

<img width="391" alt="Screen Shot 2021-03-02 at 8 16 48 PM" src="https://user-images.githubusercontent.com/1172461/109737997-0ccc6f00-7b95-11eb-88c3-79ce0768f822.png">

In this case ^^ there *is* an image located at `/assets/img/google-doc/hero.svg`, but it won't display because it's in a folder called `google-doc`. If I move the image to the `img` root, it's displayed at `/assets/img/hero.svg`.

I'm experiencing the same when referencing images in markdown. Eg:

```
<img src="/assets/img/folder/image.svg"> // Doesn't display ❌
<img src="/assets/img/image.svg"> // Does display ✅
```

Any idea what's going on here? Is there something I could add that allows the site to display images in folders?

Many thanks in advance!

**Comment by dafiulh** [comment]
Sorry, can you explain what do you expect and what happens instead?

**Comment by TedGoas** [comment]
Sorry, I expect the image to display in a browser:

<img width="446" alt="Screen Shot 2021-03-02 at 9 14 06 PM" src="https://user-images.githubusercontent.com/1172461/109742029-4654a880-7b9c-11eb-9aea-ac2e96365872.png">

---

Instead the image does not load even though the path seems to be correct

<img width="391" alt="Screen Shot 2021-03-02 at 8 16 48 PM" src="https://user-images.githubusercontent.com/1172461/109742058-5e2c2c80-7b9c-11eb-8c04-35c86c6502ac.png">

Does that make sense?

**Comment by dafiulh** [comment]
Where is the folder you store the image? And what is in the `thumb` frontmatter?
In case you don't know, all images inside `/src/posts/img` and `/src/assets/img` are copied to `/dist/assets/img` by using `addPassthroughCopy` in the [Eleventy config file](https://github.com/dafiulh/vredeburg/blob/master/.eleventy.js#L10-L11). So the `thumb` frontmatter is referencing file relative to that folder, you can change this behavior by changing this [line](https://github.com/dafiulh/vredeburg/blob/master/src/posts/posts.11tydata.js#L11).

**Comment by TedGoas** [comment]
Oh yea, those seem like the places to update this! Though I'm a bit of a JS novice, do you know how I would update those statements to preserve the subdirectory name of any subdirectory present?

**Comment by dafiulh** [comment]
Oh, it seems I misinterpret your question earlier. Yeah, nevermind.

So if you want to preserve the subdirectory when Eleventy copy the folder, just change [these lines](https://github.com/dafiulh/vredeburg/blob/master/.eleventy.js#L10-L11) with this:
```js
config.addPassthroughCopy('src/assets/img/');
config.addPassthroughCopy({ 'src/posts/img/': 'assets/img/' });
```
